### ISSUE TITLE
Need an implementation report

### ISSUE THREAD

**Issue by LJWatson** [w3c/uievents-code#20]
Is there an implementation report for this spec? We'll need something of the sort to exit CR.

**Comment by garykac** [comment]
Implementation report: https://w3c.github.io/uievents-code/impl-report.html

**Comment by LJWatson** [comment]
It looks like there are gaps in the implementation report for testing with things other than browsers (TV remotes etc.). Do we have implementations for all devices?

**Comment by xfq** [comment]
I just had a look at the implementation report. WebKit now supports `KeyboardEvent.code`[1]. It's shipped in Safari too[2]. Here's my manual test results in Safari 11.0.3 on 10.13.3:

* In Alphanumeric Section - Writing System Keys, `code` attribute values other than "IntlBackslash", "IntlRo", and "IntlYen" are supported. My keyboard does not contain these three keys so I'm not able to test them.

* In Alphanumeric Section - Functional Keys, `code` attribute values other than "ContextMenu", "ControlRight", and functional keys found on Japanese and Korean keyboards are supported. My keyboard does not contain those keys either.

* In Control Pad Section, "Delete", "End", "Home", "PageDown", and "PageUp" are supported (emulated by fn + various keys). Not sure about "Help" and "Insert".

* In Arrow Pad Section, all `code` attribute values are supported.

* I haven't tested the Numpad Section (because my MacBook does not contain a numeric keypad).

* In Function Section, "Escape" and "F1-12" are supported (with Touch Bar). Not sure about "PrintScreen", "ScrollLock", and "Pause" because of the lack of these keys.

* I haven't tested the Media Keys, because my keyboard does not contain these keys.

* In Optional Keys, "Fn" is not supported (directly). I don't know how to test "Unidentified". Not sure about other keys.

I don't have a Windows machine and therefore I'm not able to provide the test results for Microsoft Edge, although from caniuse.com[3] Edge doesn't seem to support `KeyboardEvent.code`.

-----

Test code:

```javascript
window.addEventListener("keydown", function (event) {
    let out = "KeyboardEvent: key='" + event.key + "' | code='" + event.code + "'";
    console.log(out);
}, true);
```

-----

Links:

[1] https://bugs.webkit.org/show_bug.cgi?id=149584
[2] https://webkit.org/blog/6987/release-notes-for-safari-technology-preview-15/
[3] https://caniuse.com/#feat=keyboardevent-code

**Comment by xfq** [comment]
@LJWatson I haven't found TV Keys in this implementation report. They're in the uievents-key's implementation report tho.

**Comment by garykac** [comment]
Back before -key and -code were extracted from UIEvents, There were tables (many from other industry specs) that covered media keys so that those devices would be covered by the spec if those keys were present.

We've made use of some of these values for multimedia keyboards, and we expect that some browsers (e.g., browsers on TVs) would make use of a wider set of these values. Because this is a long tail of different products, we wanted to make sure that we had something specified so that manufacturers don't make up their own values for these keys.

The implementation report, however, only covers major browsers since those are the only implementations we're aware of.

We basically have 2 options:
(1) Remove values that aren't already being used on a major desktop browser and hope that the "long tail" of embedded browsers use consistent values.
(2) Keep them in the spec so that future products have consistent values, but recognize that not all of them are currently used.

Up 'til now, we've opted for (2), since it seems more future-proof. But I can understand the argument for (1).

**Comment by garykac** [comment]
@xfq For testing, you can also use: https://w3c.github.io/uievents/tools/key-event-viewer.html

**Comment by chaals** [comment]
...or (3) test with some TV browsers and media devices...

(option 1 seems pretty short-sighted, I agree)

**Comment by garykac** [comment]
The only ones I'm aware of/have access to are basically outdated versions of Chrome.

My hope is that that will change, though, if these embedded browsers become more common.

**Comment by xfq** [comment]
...or defer the unimplemented `key` and `code` attribute values to the next level/version, and move this version (the implemented parts) to REC.

**Comment by xfq** [comment]
Here are some useful comments from @frivoal: https://lists.w3.org/Archives/Public/public-webapps/2018JanMar/0028.html

-----

Summary:

* Link to test files, preferably by linking each entry in the result tables to the corresponding test if possible;
* If automated testing is not possible, file bugs against web-platform-tests and/or WebDriver, and use manual tests for now;
* Distinguish different kinds of failures in the test results;
* Rename "Yes" to "Pass";
* Add a summary of the test results;
* State why it is judged acceptable to move to PR for features with less than 2 "Yes"/"Pass".

**Comment by frivoal** [comment]
> We basically have 2 options:

There's option 3, which I would favor:

Split the spec into 2 levels, and keep only the interoperably implemented parts in level 1, and have level 2 cover all values (either by inlining or refering to level 1, plus defining the new stuff). That way you get the benefits of future interop, and you can actually wrap up level 1 and get it to REC. Also, since level 1 then only contains the stuff that is solid, people's impression of its maturity isn't tainted by the presence of things known not to exist.

**Comment by garykac** [comment]
The implementation report has been updated based on this feedback:
https://w3c.github.io/uievents-code/impl-report.html

**Comment by marcoscaceres** [comment]
closing as addressed by @garykac.
